# Generated by Django 4.2.30 on 2026-07-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0005_operator_address_line1_operator_city_and_more'),
        ('equipment', '0002_maintenancerecord_equipmentattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='logsheet.operator'),
        ),
    ]
