# Generated by Django 4.2.30 on 2026-07-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentattachment',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentattachment',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
