# Generated by Django 4.2.30 on 2026-07-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentattachment_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('rented', 'Rented'), ('maintenance', 'Under Maintenance'), ('in_transit', 'In Transit'), ('retired', 'Retired')], default='available', max_length=20),
        ),
    ]
