# Generated by Django 4.2.30 on 2026-07-13 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customerquery_client_email_customerquery_client_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0005_alter_equipment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTransit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('route_type', models.CharField(choices=[('warehouse_to_site', 'Warehouse to Site'), ('site_to_site', 'Site to Site')], max_length=30)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_transit', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transits_in', to='crm.customersite')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_records', to='equipment.equipment')),
                ('source_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transits_out', to='crm.customersite')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transits_out', to='equipment.warehouse')),
            ],
            options={
                'db_table': 'equipment_transit_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
