# Generated by Django 4.2.30 on 2026-07-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_contract_created_by_contract_quotation_customerquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquery',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='client_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='duration_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=20),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='lost_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('price_too_high', 'Price Too High'), ('found_competitor', 'Found Better Vendor'), ('budget_constraints', 'Budget Constraints'), ('delayed_delivery', 'Delayed Delivery'), ('spec_not_met', 'Specifications Not Met'), ('no_longer_needed', 'No Longer Needed'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='site_location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='customerquery',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='customerquery',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('converted', 'Converted to Quotation'), ('lost', 'Lost'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
