# Generated by Django 4.2.30 on 2026-07-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customerquery_client_email_customerquery_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='diesel_cost_covered_by',
            field=models.CharField(choices=[('us', 'Us'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
