# Generated by Django 4.2.30 on 2026-07-10 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0003_quotation_under_review_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='lost_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('price_too_high', 'Price Too High'), ('found_competitor', 'Found Better Vendor'), ('budget_constraints', 'Budget Constraints'), ('delayed_delivery', 'Delayed Delivery'), ('spec_not_met', 'Specifications Not Met'), ('no_longer_needed', 'No Longer Needed'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotation',
            name='won_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='QuotationAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_number', models.PositiveIntegerField()),
                ('amended_data', models.JSONField()),
                ('amended_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('amended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_amendments', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='quotations.quotation')),
            ],
            options={
                'db_table': 'quotation_amendments',
                'ordering': ['-amendment_number'],
                'unique_together': {('quotation', 'amendment_number')},
            },
        ),
    ]
