# Generated by Django 4.2.30 on 2026-07-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotation_lost_notes_quotation_lost_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationlineitem',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='rentalorderlineitem',
            name='duration',
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalorderlineitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalorderlineitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
