# Generated by Django 4.2.30 on 2026-07-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_contract_created_by_contract_quotation_customerquery'),
        ('invoices', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.contract'),
        ),
    ]
