# Generated by Django 4.2.30 on 2026-07-08 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logsheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_line', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning (6AM-2PM)'), ('evening', 'Evening (2PM-10PM)'), ('night', 'Night (10PM-6AM)'), ('general', 'General (Full Day)')], default='general', max_length=20)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('idle_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('breakdown_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('productive_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('meter_start', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meter_end', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logsheet_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logsheets', to='equipment.equipment')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logsheet_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logsheets',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('equipment', 'date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('license_type', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'operators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LogsheetOperator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('logsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='logsheet.logsheet')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logsheet_entries', to='logsheet.operator')),
            ],
            options={
                'db_table': 'logsheet_operators',
            },
        ),
        migrations.CreateModel(
            name='LogsheetFuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('logsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='logsheet.logsheet')),
            ],
            options={
                'db_table': 'logsheet_fuel',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LogsheetBreakdown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(choices=[('mechanical', 'Mechanical'), ('electrical', 'Electrical'), ('hydraulic', 'Hydraulic'), ('tire', 'Tire / Track'), ('engine', 'Engine'), ('no_work', 'No Work / Idle'), ('weather', 'Weather'), ('operator', 'Operator Unavailable'), ('material', 'Material Not Available'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('logsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='logsheet.logsheet')),
            ],
            options={
                'db_table': 'logsheet_breakdowns',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LogsheetApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('logsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='logsheet.logsheet')),
            ],
            options={
                'db_table': 'logsheet_approvals',
                'ordering': ['-created_at'],
            },
        ),
    ]
