# Generated by Django 4.2.30 on 2026-07-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contract_amendment_number_contract_auto_renew_and_more'),
        ('logsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsheet',
            name='contract_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logsheets', to='crm.contractlineitem'),
        ),
    ]
