# Generated by Django 4.2.30 on 2026-07-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0002_alter_logsheet_contract_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('operator_approved', 'Operator Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='draft', max_length=20),
        ),
    ]
