# Generated by Django 4.2.30 on 2026-07-08 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logsheet', '0003_alter_logsheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsheetoperator',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='date_of_hire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='operator',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='operator',
            name='overtime_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='OperatorCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cert_type', models.CharField(choices=[('license', 'License'), ('safety', 'Safety Training'), ('medical', 'Medical Clearance'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('cert_number', models.CharField(blank=True, max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, upload_to='operator_certs/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_records', to='logsheet.operator')),
            ],
            options={
                'db_table': 'operator_certifications',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='OperatorAllowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('allowance_type', models.CharField(choices=[('travel', 'Travel'), ('food', 'Food'), ('accommodation', 'Accommodation'), ('hazard', 'Hazard Pay'), ('overtime', 'Overtime Allowance'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='logsheet.operator')),
            ],
            options={
                'db_table': 'operator_allowances',
                'ordering': ['-date', 'operator__name'],
            },
        ),
        migrations.CreateModel(
            name='OperatorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning (6AM-2PM)'), ('evening', 'Evening (2PM-10PM)'), ('night', 'Night (10PM-6AM)'), ('general', 'General (Full Day)')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('deployed', 'Deployed'), ('on_leave', 'On Leave'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='logsheet.operator')),
            ],
            options={
                'db_table': 'operator_availability',
                'ordering': ['date', 'operator__name'],
                'unique_together': {('operator', 'date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning (6AM-2PM)'), ('evening', 'Evening (2PM-10PM)'), ('night', 'Night (10PM-6AM)'), ('general', 'General (Full Day)')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'On Leave'), ('holiday', 'Holiday')], default='present', max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='logsheet.operator')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', 'operator__name'],
                'unique_together': {('operator', 'date', 'shift')},
            },
        ),
    ]
