# Generated by Django 4.2.30 on 2026-07-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsheet', '0005_operator_address_line1_operator_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='license_file',
            field=models.FileField(blank=True, upload_to='licenses/'),
        ),
    ]
